config/routes.rb
Rails.application.routes.draw do 
	#routes to 'toppages#index'

	root to: 'pages#index'

	devise_for :users
	devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
        get '/users/sign_in' => 'device/sessions#create'
        get '/users/sign_in' => 'device/sessions#new'
    end

    
    resources :like, only: %i(create destroy) do
    end

    resources :posts, only: %i(new create index destroy) do
        get 'like' => 'like#create'
        get 'unlike' => 'like#destroy'
        resources :photos, only: %i(create)
        resources :comments, only: %i(create destroy)
    end

    resources :users, only: [:index, :show, :new, :create] do
	    member do
	      # get :followings
	      # get :followers
	       get :likes
	    end
  	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :post
    validates :image, presence: true
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :photos, dependent: :destroy
	has_many :like, -> { order(created_at: :desc) }, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user
	accepts_nested_attributes_for :photos
	def liked_by(user)
        like.find_by(user_id: user.id, post_id: id)
    end
    has_many :comments, dependent: :destroy
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
         # :recoverable, :rememberable, 
  validates :name, presence: true, length: { maximum: 50 }
  has_many :posts, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notive] = "投稿を削除しました"
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)  #formにてpost_idパラメータを送信して、コメントへpost_idを格納するようにする必要がある。
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
	before_action :authenticate_user!
    def create
        @like = current_user.like.build(like_params)
        # @post = @like.post
        if @like.save
            redirect_to root_path
        end
    end
    def destroy
        @like = current_user.like.find_by(like_params)
        # @post = @like.post
        if @like.destroy
            redirect_to root_path
        end
    end
    
    private
        def like_params
            params.permit(:post_id)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@posts = Post.all.order(id: :desc)
		#投稿用
        @comment = Comment.new
        #表示用
        #@comments = @post.comments
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

    

    def index
        #pages/indexでrender
        @posts = Post.find(params[:id])
        #投稿用
        @comment = Comment.new
        #表示用
        #@comments = @post.comments
    end
        
    def new
        @post = Post.new
        @post.photos.build
    end
    def create
        @post = Post.new(post_params)
        if @post.photos.present?
        @post.save
        redirect_to root_path
        flash[:notice] = "投稿が保存されました"
        else
        redirect_to root_path
        flash[:alert] = "投稿に失敗しました"
        end
    end
    def destroy
        @post.destroy
        flash[:notive] = "投稿を削除しました"
        redirect_back(fallback_location: root_path)
    end
    def index
        @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
    end
    private
        def post_params
            params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]
	def index
		@users = User.order(id: :desc)
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.order(id: :desc)
    @comment = Comment.new
	end

  def likes
    @user = User.find(params[:id])
    @posts = @user.liked_posts
    @comment = Comment.new
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
    		flash[:success] = 'ユーザを登録しました。'
    		redirect_to root_path
  	else
    		flash.now[:danger] = 'ユーザの登録に失敗しました。'
    		render :new
  	end
	end
  
 #  	def followings
 #    	@user = User.find(params[:id])
 #    	@followings = @user.followings.page(params[:page])
 #  	end
  
 #  	def followers
 #    	@user = User.find(params[:id])
 #    	@followers = @user.followers.page(params[:page])
	# end
  
 #  	def likes
 #    	@user = User.find(params[:id])
 #    	@likes = @user.feed_favorites.order(id: :desc).page(params[:page])
 #  	end
  
  	private
  		def user_params
    		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Instagram</a> <!-- ロゴ -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center">
        <% if user_signed_in? %>
          <!-- <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li> -->
          
            <li class="dropdown-item">
              <%= link_to 'My profile', user_path(current_user) %>
            </li>
            <li class="dropdown-divider"></li>
            <li class="dropdown-item">
              <%= link_to '投稿する', new_post_path %>
            </li>
            <li class="dropdown-divider"></li>
            <li class="dropdown-item">
              <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
          <!-- なぜか動かん -->
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %></a>
              <ul class="dropdown-menu">
                <li class="dropdown-item">
                  <%= link_to 'My profile', user_path(current_user) %>
                </li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item">
                  <%= link_to '投稿する', new_post_path %>
                </li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item">
                  <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>    
                </li>
              </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', new_user_registration_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Instagram2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
  	  <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/like/like_text.html.erb
<h1>like_text</h1>

app/views/pages/index.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div>
      <%= render template: 'posts/index'%>
    </div>
  </div>

<% else %>

	<div class="center jumbotron">
	    <div class="text-center">
	      <h1>Instagram</h1>
	      <h3>みんなでバエよう</h3>
	      <%= link_to 'ログイン', new_user_session_path %>
	      <h5>または</h5>
	      <%= link_to 'メールアドレスで登録', 
	      		new_user_registration_path, class: 'btn btn-lg btn-primary'%>
	    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="col-md-8 col-md-2 mx-auto">
        <div class="card-wrap">
            <div class="card">
                <div class="card-header align-items-center d-flex">
                    <%= link_to user_path(post.user), class: "no-text-decoration" do %>
                        
                        <!--%= image_tag avatar_url(post.user), class: "post-profile-icon" %-->
                    <% end %>
                    <%= link_to user_path(post.user), class: "black-color no-text-decoration",　title: post.user.name do %>
                        <strong><%= post.user.name %></strong>
                    <% end %>

                    <!-- 削除 -->
                    <% if post.user_id == current_user.id %>
                        <%= link_to 'post#delete', method: :delete, class: "ml-auto mx-0 my-auto" do %>
                            <div class="delete-post-icon">
                                削除
                            </div>
                        <% end %>
                    <% end %>
                </div>
                <% if post.photos.present? %>
                    <%= link_to(post_path(post)) do %>
                        <%= image_tag post.photos.first.image.url, class: "card-img-top" %>
                    <% end %>
                <% end %>
                <div class="card-body">
                    <div class="row parts">
                        <%# ==========ここから========== %>
                        <!-- いいね -->
                        <div id="like-icon-post-<%= post.id.to_s %>">
                            <% if post.liked_by(current_user).present? %>
                            <%= link_to "いいねを取り消す", post_unlike_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                            <% else %>
                            <%= link_to "いいね", post_like_path(post), method: :POST, remote: true, class: "love hide-text" %>
                            <% end %>
                        </div>
                        <%# ========== ここまで修正 ========== %>

                        <!--%= link_to "", "#", class: "comment" %-->
                    </div>
                        <%# 不明==========ここから==========不明！！！！ %>
                    <div id="like-text-post-<%= post.id.to_s %>">
                        <!--%= render "like_text", { like: post.like } %-->
                    </div>
                        <%# ==========ここまで修正========== %>

                    <div>
                        <span><strong><%= post.user.name %></strong></span>
                        <%= time_ago_in_words(post.created_at).upcase + "前"%><br>
                        <span><%= post.caption %></span>
                        <div class="row parts">
                            <div class="w-100">
                              <%= form_with model: [post, @comment] do |f| %>
                                <%= f.text_area :comment, placeholder: "コメント...", class: "form-control comment-input border-0"  %>
                                <%= f.submit "投稿", class: "btn-sm btn-primary" %>
                              <% end %>
                            </div>
                          <div class="comment parts">
                              <% post.comments.each do |comment| %>
                                <%= link_to user_path(post.user), class: "black-color no-text-decoration",　title: post.user.name do %>
                                    <strong><%= post.user.name %></strong>
                                <% end %>
                                <%= comment.comment %>
                                <% if post.user_id == current_user.id %>
                                  <%= link_to 'バイバイ', post_comment_path(post, comment), method: :delete %>
                                <% end %> <br>                         
                              <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<div class="main">
  <div class="">
    <div class="form-wrap">
      <div class="form-group text-center">
      </div>
      <%= form_with model: @post do |f| %>
        <div class="form-group">
          <%= f.label :caption %>
        </div>
        <div class="form-group">
          <%= f.text_field :caption %>
        </div>
        <div class="form-group">
          <%= f.fields_for :photos do |i| %>
            <%= i.file_field :image %>
          <% end %>
        </div>
        <div class="actions">
          <%= f.submit "投稿", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<h1>show</h1>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 250 }) %>" alt="">
      </div>
    </div>
    <!--%= render 'relationships/follow_button', user: @user %-->
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"> Posts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user)%>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes</a></li>
    </ul>
    <%= render template: 'posts/index'%>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 250 }) %>" alt="">
      </div>
    </div>
    <!--%= render 'relationships/follow_button', user: @user %-->
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"> Posts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user)%>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes</a></li>
    </ul>
    <%= render template: 'posts/index'%>
  </div>
</div>